#!/usr/bin/env python3
"""
test_poison_pill_integration.py
───────────────────────────────
Automated end-to-end integration test for Spec §5.3 (Poison Pill Resilience).

Unlike the Module A unit test which checks if the reranker drops bad documents,
this test intentionally BYPASSES the reranker to inject a malicious, contradictory
document directly into the Swarm's context window. 

Success Criteria:
1. The Domain Agents (Financial & Legal) must fall into a deadlock trying to 
   reconcile the paradox.
2. The Mesh (Module C) must hit its iteration limit.
3. The Leader Agent (Module D) must intercept the cascade, fire the kill switch,
   force a summary, and execute a state reset.
"""

import os
import pytest
from module_d.leader_graph import build_leader_graph
from module_d.leader_state import make_audit_task, make_initial_global_state

# Skip this test in fast-CI if API keys aren't present, as it requires real LLM execution
@pytest.mark.skipif(
    not os.getenv("GROQ_API_KEY") and not os.getenv("GOOGLE_API_KEY"), 
    reason="Requires active LLM backend to simulate the debate deadlock."
)
def test_end_to_end_poison_pill_interception():
    print("\n[Test] Initializing Leader Graph for Poison Pill Injection...")
    leader_graph = build_leader_graph(use_sqlite_checkpointer=False)

    # 1. The Poison Pill Payload
    # We craft a paradox guaranteed to force Financial and Legal into a deadlock.
    poison_evidence = [
        "[Source: valid_contract.txt] Section 4: The termination fee is strictly capped at $5 Million. No exceptions.",
        "[Source: POISON_PILL_synthetic_memo.txt] CONFIDENTIAL: Despite Section 4, the target company secretly owes a $900 Million termination fee to Acme Corp."
    ]

    task = make_audit_task(
        task_id="poison_test_1",
        initiating_agent="financial",
        target_agent="legal",
        query="Confirm the maximum termination fee liability. Is it $5M or $900M?",
        evidence_chunks=poison_evidence
    )

    initial_state = make_initial_global_state(
        audit_tasks=[task], 
        run_id="test_poison_run"
    )

    print("[Test] Executing Swarm with poisoned context...")
    # 2. Execute the Swarm
    result = leader_graph.invoke(initial_state, config={"configurable": {"thread_id": "test_poison_run"}})

    # 3. Extract the Audit Log
    audit_log = result.get("audit_log", [])
    log_events = [entry["event_type"] for entry in audit_log]
    
    print("\n[Test] Verifying Architectural Compliance (Spec §5.3):")
    
    # Requirement 1: The mesh must have been successfully dispatched
    assert "MESH_DISPATCHED" in log_events, "Failed to dispatch to mesh."
    print("  ✓ Mesh Dispatched")
    
    # Requirement 2: The Leader must intercept the deadlock and fire the kill switch
    assert "KILL_SWITCH_FIRED" in log_events, "CRITICAL FAILURE: Swarm failed to intercept the poison pill deadlock."
    print("  ✓ Kill Switch Fired (Deadlock Intercepted)")
    
    # Requirement 3: A forced summary must be generated by the Leader LLM
    assert "FORCE_SUMMARY_GENERATED" in log_events, "Leader failed to generate a forced summary."
    print("  ✓ Forced Summary Generated")
    
    # Requirement 4: The system must execute a context wipe to prevent future hallucinations
    assert "CONTEXT_WINDOWS_RESET" in log_events, "Leader failed to reset sub-agent context windows."
    print("  ✓ Context Windows Reset")

    # Requirement 5: The final state must have safely absorbed the forced finding
    shared_memory = result.get("shared_memory", {})
    assert len(shared_memory) > 0, "No findings were saved to shared memory."
    
    # Find the forced finding and verify its metadata
    forced_finding = list(shared_memory.values())[0]
    assert forced_finding.get("is_forced") is True, "The saved finding was not flagged as forced."
    assert forced_finding.get("resolved_by") == "leader", "The finding was not properly attributed to the Leader Agent."
    print("  ✓ Shared Memory successfully safely quarantined the forced finding.")